// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kinkoevtsdkgjnlhznwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpbmtvZXZ0c2RrZ2pubGh6bnduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYyNjExMjQsImV4cCI6MjA4MTgzNzEyNH0.MwEHCZclQ8aD2CneXTOpLWaZ_MHXjYTPfxtsc4JNOHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});