// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slfbznhcnzkoksobuikx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsZmJ6bmhjbnprb2tzb2J1aWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNzcyMTcsImV4cCI6MjA3MDk1MzIxN30.fzpT9HGbJ0Ebkme4RxN_bHL58FmrdSa_xfn3hVR5qSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});